export const HELP_LINES = [
  "Commands:",
  "help                         show this help",
  "pwd                          print current virtual path",
  "ls [-a] [path]               list your team's simulated host",
  "cd <path>                    change virtual directory",
  "cat <file>                   read virtual file",
  "grep <term> <path>           search virtual files",
  "find [path] [term]           find virtual paths",
  "tree [-a] [path]             render a virtual directory tree",
  "head [-n count] <file>       print first lines",
  "tail [-n count] <file>       print last lines",
  "touch <file>                 create or update a virtual file",
  "mkdir <path>                 create a virtual directory",
  "rm <path>                    remove an unlocked virtual node",
  "cp <from> <to>               copy a virtual node",
  "mv <from> <to>               move a virtual node",
  "chmod <mode> <path>          tag a virtual node with a mode",
  "sudo <command>               run an allowed simulated admin command",
  "su [user]                    simulated user switch prompt",
  "id                           show simulated identity",
  "groups                       show simulated groups",
  "uname [-a]                   show simulated kernel info",
  "date                         show match server time",
  "uptime                       show match uptime",
  "df                           show simulated disk usage",
  "du [path]                    estimate virtual path size",
  "wc <file>                    count lines, words, bytes",
  "echo [text]                  print text",
  "man [command]                show command notes",
  "which <command>              locate a simulated command",
  "alias                        list simulated aliases",
  "whoami                       show your simulated user",
  "hostname                     show your simulated host",
  "env                          show simulated environment",
  "ps                           show simulated processes",
  "kill <pid>                   simulate process control",
  "history                      show your command history",
  "clear                        clear client screen when supported",
  "scan <red|blue>              reveal attack surfaces",
  "crack <perimeter|logs|vault> advance cracking against enemy team",
  "plant <path>                 plant noisy evidence on enemy host",
  "clean <path>                 remove planted files from your host",
  "harden <perimeter|logs|vault> raise defense for your host",
  "submit <token>               submit enemy token to win",
  "chat <message>               broadcast a message",
  "score                        show score"
];

export const COMMAND_NAMES = HELP_LINES
  .slice(1)
  .map((line) => line.trim().split(/\s+/)[0])
  .filter(Boolean);
